config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "schedules#index"

  resources :schedules do
    collection do
      get 'api_data'
    end
  end

  resources :client_info_names, only: [:index ,:create ,:edit ,:update]

  resources :clients_info, only: [:index , :create]

  resources :process_machines, only: [:index ,:create]

  resources :comments, only: [:create]

end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :start_date , presence: true 
    validates :end_date   , presence: true 
    validates :client_info_id ,presence: true
    validates :process_machine_id , presence: true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!, expect: [:new]
  before_action :set_client_info_names, expect: [:index , :new]
  protect_from_forgery except: :create

  def index
    @comments = Comment.order(id: "DESC")
    @clients_info_name = ClientsInfoName.all
  end

  def new
    @process_machine = ProcessMachine.all
    @schedule = Schedule.new
    @client_info = ClientInfo.last  
  end

  def create
    @schedule = Schedule.new(schedule_params)

    if @schedule.save
      render json: @schedule, status: :created
    else
      render json: @schedule.errors, status: :unprocessable_entity
    end
  end

  def api_data
    @client_info = ClientInfo.last
    @pm_tasks = ProcessMachine.all
    render json: {
      client_info: @client_info,
      pm_tasks: @pm_tasks
    }
  end

  private

  def schedule_params
    params.require(:schedule).permit(:client_info_id, :start_date, :end_date, :process_machine_id)
  end

  def set_client_info_names
    @client_info_name = ClientsInfoName.first
  end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/index.html.erb
<%= render "shared/main_header" %>

<div class="main-container">
    <div class="body-top-wrapper">
        <% if user_signed_in? %>
          <div class="login_user_name">ログイン中 <%= current_user.first_name  %></div>
        <% else %>
          <div class="login_user_name">ログインしていません</div>
        <% end %>
        <% if user_signed_in? && current_user.admin_true == true %>
          <% if @clients_info_name.any? %>
            <%= link_to "+スケジュールを追加" , clients_info_index_path ,class:"add-schedule-btn" %>
          <% else %>
            <p>※顧客情報名称が未登録です</p>
          <% end %>
        <% end %>
    </div>
    <div id="app">
    <div v-if="loading">ページをリロードしてください </div>
    <div v-else="loading">
      <div id="gantt-content" class="gantt-content">
        <div class="gantt-task" ref="task">
          <div class="gantt-task-title" >

              <div class="task-item">顧客名</div>
              <% if @client_info_name.present? %>
              <% (1..10).each do |i| %>
                <% column_name = "clients_info#{i}_name" %>
                  <% if @client_info_name[column_name].present? %>
                    <div class="task-item"><%= @client_info_name[column_name] %></div>
                  <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="gantt-calendar" class="gantt-calendar" :style="`width:${calendarViewWidth}px`" ref="calendar">
          <div id="gantt-date" class="gantt-date">
            <div class="gantt-year-month">
              <div v-for="(calendar,index) in calendars" :key="index">
                <div class="calendar-date" :style="`width:${calendar.calendar*block_size}px;left:${calendar.start_block_number*block_size}px`">
                  {{calendar.date}}
                </div>
              </div>
            </div>
          </div>
          <div id="gantt-day" class="gantt-day">
            <div v-for="(calendar,index) in calendars" :key="index">
              <div v-for="(day,index) in calendar.days" :key="index">
                <div class="day-blocks" :class="{'saturday': day.dayOfWeek === '土', 'sunday': day.dayOfWeek ==='日' , 'today-pos': calendar.year=== today.year() && calendar.month === today.month() && day.day === today.date()}" :style="`width:${block_size}px;left:${day.block_number*block_size}px`">
                  <span>{{ day.day }}</span>
                  <span>{{ day.dayOfWeek }}</span>
                </div>
              </div>
            </div>
          </div>
          <div id="gantt-height" class="gantt-height">
            <div v-for="(calendar,index) in calendars" :key="index">
              <div v-for="(day,index) in calendar.days" :key="index">
                <div class="border-height" :class="{'saturday': day.dayOfWeek === '土', 'sunday': day.dayOfWeek ==='日'}" :style="`width:${block_size}px;left:${day.block_number*block_size}px;height:${calendarViewHeight}px`">

                </div>
              </div>
            </div>
          </div>
          <div id="gantt-bar-area" class="gantt-bar-area" :style="`width:${calendarViewWidth}px;height:${calendarViewHeight}px`">
          </div>
        </div>
      </div>
    </div>
    </div>

</div>

<div class="sidebar" id="sidebar">
  <div class="comment-box">
    <div id="comment_list"></div>
    <% @comments.each do |c|%>
      <div class="comment_block">
        <div class="comment_name_box"><%= content_tag :div,c.user&.first_name,class:"comment_name" %></div>
        <%= c.comment_data%>
      </div>
    <% end %>
  </div>
  <%= form_with model:@comment, url:comments_path, id:"comment_form" , class:"comment_form" do |f| %>
    <%= f.text_field :comment_data , class:"comment_input" , id:"comment_input" %>
    <%= f.submit '投稿' , class:"comment_btn" , id:"comment_btn" %>
  <% end %>
</div>

<% if user_signed_in? %>
  <div id="openButton">< COMMENTS</div>
  <!-- <div id="under_openButton">^ 負荷量 ^</div> -->
<% end %>

<script>
  const buildHTML = (XHR) =>{
      const item = XHR.response.comment;
      const html = `
        <div class="comment_block">
          <div class="comment_name_box">
            <%= content_tag :div, current_user.first_name, class: "comment_name" %>
          </div>
            ${item.comment_data}
        </div>`;
      return html;
  };

  const form = document.getElementById('comment_form').addEventListener('submit', (e) =>{
    e.preventDefault();
    const commentData = new FormData(e.target);

    const XHR = new XMLHttpRequest();
    XHR.open("POST", "/comments", true);
    XHR.responseType = "json";
    XHR.send(commentData);
    XHR.onload = () => {
      if (XHR.status != 200) {
        alert(`Error ${XHR.status}: ${XHR.statusText}`);
        return null;
      };
      const list = document.getElementById("comment_list");
      const formText = document.getElementById("comment_input");
      list.insertAdjacentHTML("afterend", buildHTML(XHR));
      formText.value = "";
    };
  });

  document.getElementById('openButton').addEventListener('click', function() {
    const sidebar = document.getElementById('sidebar');
    const comment_btn = document.getElementById('openButton');
    if (sidebar.style.width == '0px' || sidebar.style.width == '') {
      sidebar.style.width = '350px';
      sidebar.style.right = '0';
      comment_btn.style.right = '350px';
    } else {
      sidebar.style.width = '0';
      sidebar.style.right = '-350px';
      comment_btn.style.right = '0';
    }
  });

  const app = Vue.createApp({
    data(){
      return{
        loading:true,
        data:null,
        start_month:'',
        end_month:'',
        block_size:25,
        block_number:0,
        calendars:[],
        inner_width: '',
        inner_height: '',
        task_width: '',
        task_height: '',
        today:moment(),
      };
    },
    methods:{
      async fetchData() {
        try {
          const response = await fetch('https://jsonplaceholder.typicode.com/todos');
          const result = await response.json();
          
          this.data = result;
        } catch (error) {
          console.error('データの取得に失敗しました。ページをリロードしてください', error);
          this.reloadOnCatch();
        } finally {
          this.loading = false;
        }
      },
      reloadOnCatch() {
        window.location.reload();
      },
      getDays(year, month, block_number) {
        const dayOfWeek = ['日', '月', '火', '水', '木', '金', '土'];
        let days = [];
        let date = moment(`${year}-${month}-01`);
        let num = date.daysInMonth();
        for (let i = 0; i < num; i++) {
          days.push({
            day: date.date(),
            dayOfWeek: dayOfWeek[date.day()],
            block_number
          })
          date.add(1, 'day');
          block_number++;
        }
        return days;
      }, 
      getCalendar() {
        let block_number = 0;
        let days;
        let start_month = moment()
        let end_month = moment().add(12, 'months')
        let between_month = end_month.diff(start_month, 'months')
        for (let i = 0; i <= between_month; i++) {
          days = this.getDays(start_month.year(), start_month.format('MM'), block_number);
          this.calendars.push({
            date: start_month.format('YYYY/MM'),
            year: start_month.year(),
            month: start_month.month(), 
            start_block_number: block_number,
            calendar: days.length,
            days: days
          })
          start_month.add(1, 'months')
          block_number = days[days.length - 1].block_number
          block_number++;
        }
        return block_number;
      },    
      getWindowSize() {
          this.inner_width = window.innerWidth;
          this.inner_height = window.innerHeight;
          this.task_width = this.$refs.task.offsetWidth;
          this.task_height = this.$refs.task.offsetHeight;
      },
      todayPosition() {
        this.$refs.calendar.scrollLeft = this.scrollDistance
      },
    },
    computed: {
      calendarViewWidth() {
        return this.inner_width - this.task_width;
      },
      calendarViewHeight() {
        return this.inner_height - this.task_height - 48 - 60 - 80;
      },
      scrollDistance() {
        let start_date = moment(this.start_month);
        let between_days = this.today.diff(start_date, 'days')
        return between_days* this.block_size;
      },
    },
    mounted() {
      this.fetchData();
      this.getCalendar();
      this.getWindowSize();
      this.$nextTick(() => {
      this.todayPosition();
      });
      window.addEventListener('resize', this.getWindowSize);
    }
  }).mount('#app')

</script>