config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "schedules#index"

  resources :schedules do
    collection do
      get 'api_data'
    end
  end

  resources :client_info_names, only: [:index ,:create ,:edit ,:update]

  resources :clients_info, only: [:index , :create]

  resources :process_machines, only: [:index ,:create]

  resources :comments, only: [:create]

end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_main_footer.html.erb
<div class="footer-wrapper">
    <p>hints</p>
</div>

app/views/shared/_main_header.html.erb
<header>
    <div class="header-wrapper">
        <div class="header-title">ProCon</div>
        <div class="header-nav">
            <ul class="nav-items">
                <% if user_signed_in? %>
                    <li><%= link_to "ログアウト" , destroy_user_session_path ,data:{turbo_method: :delete},class: "nav-item"  %></li>
                <% else %>
                    <li><%= link_to "ログイン" , new_user_session_path ,class: "nav-item" %></li>
                    <li><%= link_to "新規登録" , new_user_registration_path,class: "nav-item" %></li>
                <% end %>
                <% if user_signed_in? && current_user.admin_true == true %>
                    <li><%= link_to "設備/工程登録" , process_machines_path ,class: "nav-item" %></li>
                    <% if @client_info_name.present? %>
                        <li><%= link_to "顧客情報名称編集"  ,edit_client_info_name_path(ClientsInfoName.first.id),class: "nav-item" %></li>
                    <% else %>
                        <li><%= link_to "顧客情報名称登録" , client_info_names_path ,class: "nav-item" %></li>
                    <% end %>
                <% end %>
            </ul>
        </div>
    </div>
</header>

app/views/shared/_second_main_header.html.erb
<header>
    <div class="header-wrapper">
        <div class="header-title">ProCon</div>
        <div class="header-nav">
            <ul class="nav-items">
                <li><%= link_to "作業を完了せず戻る" , root_path ,class: "nav-item" %></li>
            </ul>
        </div>
    </div>
</header>